name: Notify on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'stage' || github.event.pull_request.base.ref == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Notify-Merge Script
        run: node .github/workflows/notify-merge.js
        env:
          OKAN_SLACK_WEBHOOK: ${{ secrets.OKAN_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_EVENT_PATH: './event.json'
          GITHUB_SHA: ${{ github.event.pull_request.merge_commit_sha }}
